## Sizing the screen/display
screen-width: 1200
screen-height: 800
pixel-scale: 50

## Main colors
background-color: [50, 50, 50]
robot-color:      [200, 140, 80]
wheel-color:      [100, 70, 70]

## Ultrasonic colors
ultrasonic-color: [50, 160, 200]
average-color:    [120, 180, 20]

## Size of average-position indicators
average-draw-sz:  1

## Robot body definition
robot-outline:
  - [ 1.24, 3 ]
  - [ 3, 1.24 ]
  - [ 3, -1.24 ]
  - [ 1.24, -3 ]
  - [ -1.24, -3 ]
  - [ -3, -1.24 ]
  - [ -3, 1.24 ]
  - [ -1.24, 3 ]

## Wheels bounding rectangle (x1, x2, y1, y2)
wheel-outline: [-9, 9, 2, 2]

## Ultrasonic scaling factor (eg. if metric to imperial needed, basis here is imperial)
ultrasonic-scale: 1

## Defining ultrasonic positions
ultrasonic:
  u1:
    location: [1.2, -2.58]
    rotation: 180
  u2:
    location: [-1.2, -2.58]
    rotation: 180
  u3:
    location: [-2.97, 0]
    rotation: 270
  u4:
    location: [0, 2.97]
    rotation: 0
  u5:
    location: [2.97, 0]
    rotation: 90
