interface-port: 3001

simmer-sensors:
  us:
    - u0
    - u1
    - u2
    - u3
    - u5
  comp: c1
  gyro: g1

simmer-to-act:
  u0: '0'
  u1: '1'
  u2: '2'
  u3: '3'
  u4: '4'
  u5: '5'
  c1: c
  g1: g

motion-api:
  F:  0x01
  B:  0x02
  L:  0x03
  R:  0x04
  SL: 0x05
  SR: 0x06
  M:  0x07
  H:  0x08
  P:  0x09

motion-needs-val:
  - F
  - B
  - L
  - R
  - SL
  - SR

sensor-api:
  S:       0x10
  U:       0x20
  G:       0x30
  C:       0x40
